### ISSUE TITLE
plugin fails to establish connection to the API

### ISSUE THREAD

**Issue by dthpulse** [mirceaulinic/alerta-blackout-regex#15]
Hi

plugin is failing to be loaded and I can see following in alerta.log:

```
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc86a8265c0>: Failed to establish a new connectio
n: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /blackouts (Caused by
NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc86a8265c0>: Failed to establish a new connection: [Errno 111] Conn
ection refused'))
```
This looks like it tries to connect to localhost port 8080, but there is no service listening on this port.

**Comment by dthpulse** [comment]
solved by adding configuration to nginx:

```
upstream backend {
        server localhost:8080 fail_timeout=0;
}
```
