### ISSUE TITLE
blackout_regex.py doesn't include env variables needed by alerta-client

### ISSUE THREAD

**Issue by dthpulse** [mirceaulinic/alerta-blackout-regex#16]
While our alerta is working fine with environment variables I found that blackout-regex plugin doesn't. While it imports Client from alertaclient.api, environment variables like **ALERTA_API_KEY** and **ALERTA_ENDPOINT** are not loaded and so it's using default ones: http://localhost:8080 and empty API KEY. So it doesn't work in custom configuration supported by Alerta itself.

How I fixed it in blackout_regex.py is by adding:

```
'''
requires python-dotenv module
and environment variables to be set in /etc/environment file:
ALERTA_API_KEY=<API KEY>
ALERTA_ENDPOINT=https://alerta-server.com/api
'''
from dotenv import load_dotenv
from pathlib import Path
dotenv_path = Path('/etc/environment')
load_dotenv(dotenv_path=dotenv_path)
```

Do you have any other suggestion why it doesn't work? If not, can I create PR to add code above to yours?

Thank you

**Comment by mirceaulinic** [comment]
Hi @dthpulse - only now seeing this issue. Would you mind trying with version 3.0.0, just released a few minutes ago? It no longer gathers the Blackouts via the API, so this should no longer be an issue. Let me know! 😄

**Comment by dthpulse** [comment]
Hi @mirceaulinic,
that doesn't work due to exception:

```
2022-11-04 10:38:27,551 alerta.app[134033]: [ERROR] 'dict' object has no attribute 'environment' request_id=a6424c3b-9d36-46cd-b14f-4d3ac3e05e41 ip=10.10.113.148
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/alerta/utils/api.py", line 41, in process_alert
    alert = plugin.pre_receive(alert, config=wanted_config)
TypeError: pre_receive() got an unexpected keyword argument 'config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/alerta/webhooks/custom.py", line 55, in custom
    alert = process_alert(alert)
  File "/usr/local/lib/python3.9/dist-packages/alerta/utils/api.py", line 43, in process_alert
    alert = plugin.pre_receive(alert)  # for backward compatibility
  File "/usr/local/lib/python3.9/dist-packages/blackout_regex.py", line 198, in pre_receive
    return self._apply_blackout(alert)
  File "/usr/local/lib/python3.9/dist-packages/blackout_regex.py", line 103, in _apply_blackout
    if blackout.environment:
AttributeError: 'dict' object has no attribute 'environment'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/usr/local/lib/python3.9/dist-packages/alerta/auth/decorators.py", line 53, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/alerta/webhooks/custom.py", line 73, in custom
    raise ApiError(str(e), 500)
alerta.exceptions.ApiError: 'dict' object has no attribute 'environment'
```

**Comment by mirceaulinic** [comment]
Could you provide more details about your setup? What Alerta version is this? Do you also have the usual `blackout` plugin enabled?

**Comment by dthpulse** [comment]
sure, here are the details:
```
alerta                           8.5.1
alerta-blackout-regex            3.0.0
alerta-server                    8.7.0
```
blackout plugin is enabled as well.

**Comment by dthpulse** [comment]
Hi @mirceaulinic, 
any hint on this?

**Comment by mirceaulinic** [comment]
Please re-open if the issue persists after upgrading to version 3.1.0.
