### ISSUE TITLE
Crash on startup in docker-container

### ISSUE THREAD

**Issue by jinithin** [mirceaulinic/alerta-blackout-regex#9]
I'm experiencing crashes when using the latest version of alerta-web from docker (`f74916a2cebd`).
Installation of the plugin is done via pip (`/venv/bin/pip install alerta-blackout-regex`).

```
2021-01-18 09:11:27,311 alerta.app[52]: [ERROR] Expecting value: line 1 column 1 (char 0) request_id=aa0e0b32-7c2f-4635-931c-aa8f707bb809 ip=xxx.xxx.xxx.xxx
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/alerta/webhooks/custom.py", line 52, in custom
    alert = process_alert(alert)
  File "/venv/lib/python3.7/site-packages/alerta/utils/api.py", line 76, in process_alert
    updated = plugin.post_receive(alert)  # for backward compatibility
  File "/venv/lib/python3.7/site-packages/blackout_regex.py", line 44, in post_receive
    blackouts = client.get_blackouts()
  File "/venv/lib/python3.7/site-packages/alertaclient/api.py", line 191, in get_blackouts
    r = self.http.get('/blackouts', query)
  File "/venv/lib/python3.7/site-packages/alertaclient/api.py", line 576, in get
    return self._handle_error(response)
  File "/venv/lib/python3.7/site-packages/alertaclient/api.py", line 608, in _handle_error
    resp = response.json()
  File "/venv/lib/python3.7/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Any ideas? :)

**Comment by mirceaulinic** [comment]
Hi @jinithin. Sorry for the late reply here.
I should try with a newer Alerta version, perhaps the plugin is being invoked before the API is initialized.

For starters, could you check the following for me please (just start a Python console in the Alerta server container):

```python
>>> from alertaclient.api import Client
>>> client = Client()
>>> blackouts = client.get_blackouts()
>>> blackouts
[]
```

Cheers!

**Comment by mirceaulinic** [comment]
Hey @jinithin - I would recommend you to upgrade to version 3.0.0, which should normally help alleviate this issue as well.

**Comment by jinithin** [comment]
Thanks for the suggestion. We've since abandoned the idea of regex matching in Alerta, so this is no longer needed for us.
Closing this issue.

Again, thanks anyways.
